version: '3.9'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    command: sleep infinity
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=async_task
    depends_on:
      - db
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: async_task
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
